name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create landing page
        run: |
          # Create a simple landing page
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Attendance System</title>
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
                  .btn { display: inline-block; padding: 15px 30px; background: #007bff; 
                         color: white; text-decoration: none; border-radius: 5px; margin-top: 20px; }
              </style>
          </head>
          <body>
              <h1>Attendance Management System</h1>
              <p>This Flask app is not hosted on GitHub Pages (static only).</p>
              <p>Check the repository for setup instructions.</p>
              <a href="https://github.com/yourusername/yourrepo" class="btn">View on GitHub</a>
          </body>
          </html>
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          # Exclude Python files from the deployment
          ignore_files: |
            app.py
            requirements.txt
            migrations/
            templates/
            *.db

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
